import type { ProductDefinitionInput } from '../schema';

/**
 * Placeholder product used until the real smart-desk model lands.
 * The model is generated by `scripts/generate-placeholder-model.mjs`.
 */
export const placeholderDesk: ProductDefinitionInput = {
  id: 'placeholder-desk',
  name: 'Studio Desk',
  description: 'A placeholder desk that exercises every option type of the configurator.',
  model: { src: '/models/placeholder-desk.glb' },
  basePrice: 890,
  currency: 'EUR',

  parts: [
    { id: 'top', label: 'Desk top', nodes: ['Top'], group: 'Surface' },
    { id: 'legs-loop', label: 'Loop legs', nodes: ['Leg_A_Left', 'Leg_A_Right'], group: 'Base' },
    {
      id: 'legs-aframe',
      label: 'A-frame legs',
      nodes: ['Leg_B_Left', 'Leg_B_Right'],
      group: 'Base',
    },
    { id: 'drawer', label: 'Drawer', nodes: ['Drawer'], group: 'Accessories', optional: true },
    {
      id: 'cable-tray',
      label: 'Cable tray',
      nodes: ['CableTray'],
      group: 'Accessories',
      optional: true,
    },
  ],

  optionGroups: [
    {
      id: 'width',
      type: 'dimension',
      label: 'Width',
      axis: 'x',
      unit: 'cm',
      targets: ['top', 'cable-tray'],
      defaultOptionId: 'w140',
      options: [
        { id: 'w120', label: '120', value: 120, scale: 120 / 140, priceDelta: -60 },
        { id: 'w140', label: '140', value: 140, scale: 1 },
        { id: 'w160', label: '160', value: 160, scale: 160 / 140, priceDelta: 90 },
      ],
    },
    {
      id: 'top-finish',
      type: 'material',
      label: 'Top finish',
      targets: ['top'],
      defaultOptionId: 'oak',
      options: [
        { id: 'oak', label: 'Natural oak', material: { color: '#d1ad80', roughness: 0.6 } },
        {
          id: 'walnut',
          label: 'Walnut',
          material: { color: '#5b3b2a', roughness: 0.55 },
          priceDelta: 120,
        },
        { id: 'white', label: 'Matte white', material: { color: '#f2f1ec', roughness: 0.7 } },
        { id: 'black', label: 'Matte black', material: { color: '#1c1c1e', roughness: 0.75 } },
      ],
    },
    {
      id: 'leg-style',
      type: 'variant',
      label: 'Leg style',
      defaultOptionId: 'loop',
      options: [
        { id: 'loop', label: 'Loop', parts: ['legs-loop'] },
        { id: 'aframe', label: 'A-frame', parts: ['legs-aframe'], priceDelta: 80 },
      ],
    },
    {
      id: 'frame-finish',
      type: 'material',
      label: 'Frame finish',
      targets: ['legs-loop', 'legs-aframe', 'cable-tray'],
      defaultOptionId: 'graphite',
      options: [
        {
          id: 'graphite',
          label: 'Graphite',
          material: { color: '#1f1f22', roughness: 0.45, metalness: 0.8 },
        },
        {
          id: 'silver',
          label: 'Brushed silver',
          material: { color: '#c7c9cc', roughness: 0.35, metalness: 0.9 },
          priceDelta: 40,
        },
        {
          id: 'brass',
          label: 'Brass',
          material: { color: '#b08d57', roughness: 0.3, metalness: 1 },
          priceDelta: 140,
        },
      ],
    },
    {
      id: 'drawer',
      type: 'toggle',
      label: 'Drawer',
      description: 'A slim drawer mounted under the right side of the top.',
      part: 'drawer',
      defaultOptionId: 'with',
      options: [
        { id: 'without', label: 'None', visible: false },
        { id: 'with', label: 'Included', visible: true, priceDelta: 150 },
      ],
    },
    {
      id: 'cable-tray',
      type: 'toggle',
      label: 'Cable tray',
      part: 'cable-tray',
      defaultOptionId: 'without',
      options: [
        { id: 'without', label: 'None', visible: false },
        { id: 'with', label: 'Included', visible: true, priceDelta: 49 },
      ],
    },
  ],
};
